
steps:
  # Checkout repository
  - checkout: self

  - task: FlutterInstall@0
    displayName: 'Install latest Flutter version'
    inputs:
      channel: 'stable'
      version: 'latest'

  - task: Bash@3
    displayName: 'Build flutter module for Android'
    inputs:
        filePath: '$(FlutterToolPath)/flutter'
        arguments: 'build aar --build-number=$(FlutterModuleVersion)'
        workingDirectory: '$(system.defaultworkingdirectory)/my_flutter_module'
  
  - task: MavenAuthenticate@0
    displayName: 'Authenticate DevOps Maven repository'
    inputs:
      artifactsFeeds: 'sample_feed'

  - task: Bash@3
    displayName: 'Deploy com.example.my_flutter_module:flutter to DevOps Maven repository'
    inputs:
      targetType: inline
      script: |
        mvn deploy:deploy-file -DrepositoryId="sample_feed" \
          -Durl="https://philippmanstein.pkgs.visualstudio.com/Flutter%20AAR%20Module%20Maven%20Artifacts%20Sample/_packaging/sample_feed/maven/v1" \
          -Dfile="$(system.defaultworkingdirectory)/my_flutter_module/build/host/outputs/repo/com/example/my_flutter_module/flutter/$(FlutterModuleVersion)/flutter-$(FlutterModuleVersion).module" \
          -DgroupId="com.example.my_flutter_module" \
          -DartifactId="flutter" \
          -Dversion="$(FlutterModuleVersion)" \
          -Dclassifiers="debug,profile,release" \
          -Dtypes="aar,aar,aar" \
          -Dfiles="$(system.defaultworkingdirectory)/my_flutter_module/build/host/outputs/repo/com/example/my_flutter_module/flutter/$(FlutterModuleVersion)/flutter-$(FlutterModuleVersion)-debug.aar,$(system.defaultworkingdirectory)/my_flutter_module/build/host/outputs/repo/com/example/my_flutter_module/flutter/$(FlutterModuleVersion)/flutter-$(FlutterModuleVersion)-profile.aar,$(system.defaultworkingdirectory)/my_flutter_module/build/host/outputs/repo/com/example/my_flutter_module/flutter/$(FlutterModuleVersion)/flutter-$(FlutterModuleVersion)-release.aar"